### ISSUE TITLE
Критическая ошибка, ломающая пабсаб

### ISSUE THREAD

**Issue by Urantij** [Urantij/TwitchSimpleLib#11]
[16:07:45] crit: TwitchSimpleLib.Irc.WsConnection
      WsConnection.Disposing
System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.Cancel()
   at TwitchSimpleLib.Irc.PingManager.Stop()
   at TwitchSimpleLib.Pubsub.TwitchPubsubClient.ConnectionDisposing(Object sender, Exception e)
   at TwitchSimpleLib.Irc.WsConnection.Dispose(Exception e)

**Comment by Urantij** [comment]
Похоже, очень редко понг может прийти после диспоза соединения? Или соединение рвётся в микро окно получения понга? В любом случае, достаточно добавить трай катч вокруг отмены, не вижу сценария, когда нужно делать что-то иное, если токен уже диспозед.
